[project]
name = "energyplus-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dill>=0.4.0",
    "doclayout-yolo>=0.0.4",
    "dotenv>=0.9.9",
    "ftfy>=6.3.1",
    "google-genai>=1.53.0",
    "gradio>=6.0.2",
    "huggingface-hub<1.0",
    "markdownify>=1.2.2",
    "mineru>=2.6.7",
    "omegaconf>=2.3.0",
    "onnxruntime>=1.20.1",
    "pyclipper>=1.4.0",
    "pydantic>=2.12.4",
    "qdrant-client[fastembed]>=1.16.1",
    "requests>=2.32.5",
    "ruff>=0.14.8",
    "shapely>=2.1.2",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
    "transformers>=4.57.3",
    "typer>=0.20.0",
    "ultralytics>=8.3.237",
    "vllm>=0.12.0",
]


[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "B",
    "C4",
    "UP",
    "SIM",
    "RUF",
    "N",]

ignore = [
    "E501", # Line too long
    "N805",
    "N806"
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
